<a href="https://colab.research.google.com/github/JPalaciosCh/ciclo_1_Programacion_101/blob/main/06_numpy_arrays_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


# **NumPy Arrays**


**Objetivo**

El objetivo de este laboratorio es brindar una comprensión profunda y práctica de la biblioteca NumPy en Python, una herramienta esencial para el cálculo numérico y el análisis en data science.


**Índice del Laboratorio**

- 1. Introducción y Configuración
- 2. Creación de Arrays
- 3. Propiedades de los Arrays
- 4. Operaciones Básicas
- 5. Indexación y Slicing
- 6. Manipulación de la Forma
- 7. Broadcasting
- 8. Álgebra Lineal


## 1. Introducción y Configuración

**¿Qué es NumPy?**

NumPy (Numerical Python) es una librería esencial en Python para el cálculo numérico y el análisis de datos. Proporciona:


- **Arrays multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.
- **Funciones matemáticas:** Operaciones vectorizadas para realizar cálculos rápidos y eficientes.
- **Herramientas avanzadas:** Funciones para álgebra lineal, transformadas de Fourier, generación de números aleatorios, y más.


**Instalación y Configuración**

Antes de comenzar, asegúrate de tener NumPy instalado en tu entorno de Python. Puedes instalarlo usando pip:

In [ ]:
!pip3 install numpy ==1.26.1 #instala la versión especifica

In [ ]:
!pip3 install numpy --upgrade --force-reinstall # fuerza la actualización de numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 56.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.1.3 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.1.3 which is incompatible.
langchain 0.3.7 requires numpy<2,>=1; python_version < "3.12", but you have numpy 2.1.3 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.1.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.1.3 which is incompatible.
pytensor 2.26.3 requires numpy<2,>=1.17.

In [ ]:
%%capture
!pip3 install numpy as np
#capture elimina la salida

In [ ]:
# Instalación
!pip install numpy

# Importación y verificación de versión
import numpy as np
print("Versión de NumPy:", np.__version__)


Versión de NumPy: 1.26.4


In [ ]:
np.__version__

'1.26.4'

## 2. Creación de Arrays

Los arrays son la base de NumPy y representan colecciones de elementos del mismo tipo de datos. Veamos cómo crearlos de diferentes maneras.

### 2.1. Crear un Array desde una Lista



**Ejemplo 1:** Array Unidimensional

In [ ]:
# Array unidimensional desde una lista
array_1d = np.array([10, 20, 30, 40])
print("Array 1D:", array_1d)


**Ejemplo 2:** Array Multidimensional


In [ ]:
# Array bidimensional desde una lista de listas
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)


**Ejercicios**

Crea un array unidimensional con los números del 5 al 15.


In [ ]:
array_1d = np.array(list(range(5, 16)))
print(array_1d)
array_1d.shape

[ 5  6  7  8  9 10 11 12 13 14 15]


(11,)

Genera un array bidimensional de 2 filas y 3 columnas con números decimales.


In [ ]:
array_2d = np.array([[1.5, 2.5, 3.2],
                     [4.1, 5.1, 6.1]])
print(array_2d)
array_2d.shape

[[1.5 2.5 3.2]
 [4.1 5.1 6.1]]


(2, 3)

Crea un array tridimensional de forma (2, 2, 2) con números enteros.

In [ ]:
array_2d_b = np.array([[[4, 4],
                       [6, 6]],
                       [[5, 5],
                       [7, 7,]]] )
print(array_2d_b)
array_2d_b.shape

[[[4 4]
  [6 6]]

 [[5 5]
  [7 7]]]


(2, 2, 2)

### 2.2. Arrays Predefinidos

NumPy ofrece funciones para crear arrays con valores predefinidos, lo cual es útil para inicializar matrices o vectores.

**Ejemplo 1:** Arrays de Ceros y Unos

In [ ]:
np.zeros((2, 5, 5)) # la dimensionalidad se construye de derecha a izquierda z, y, x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# Array de ceros de forma (3, 3)
zeros_array = np.zeros((3, 3))
print("Array de ceros:\n", zeros_array)

# Array de unos de forma (2, 4)
ones_array = np.ones((2, 4))
print("Array de unos:\n", ones_array)


In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

**Ejemplo 2:** Array de Valores Constantes


In [ ]:
# Array lleno con el valor 7 de forma (3, 2)
full_array = np.full((3, 2), 7)
print("Array lleno de 7:\n", full_array)


**Ejercicios**

Crea un array de ceros de forma (5, 5).


In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Genera un array de unos de forma (4, 1).


In [ ]:
np.ones((4, 1))

array([[1.],
       [1.],
       [1.],
       [1.]])

Crea un array lleno con el número pi (π) de forma (2, 3).

In [ ]:
import math
np.full((2,3), math.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [ ]:
np.full((2,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

### 2.3. Arrays con Rangos

Puedes crear arrays con secuencias de números utilizando funciones como arange y linspace.

**Ejemplo 1:** Usando arange


In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.arange(0, 101, 25)

array([  0,  25,  50,  75, 100])

In [ ]:
# Números del 0 al 9
arange_array = np.arange(10)
print("Array con arange:", arange_array)

# Números del 5 al 20 con paso de 3
step_array = np.arange(5, 21, 3)
print("Array con paso de 3:", step_array)


**Ejemplo 2:** Usando linspace


In [ ]:
np.linspace(0, 100, 5) #5 numeros igualmente espaciados ente 0 y 100 (float)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# 5 números igualmente espaciados entre 0 y 1
linspace_array = np.linspace(0, 1, 5)
print("Array con linspace:", linspace_array)

# 4 números igualmente espaciados entre 10 y 50
linspace_array2 = np.linspace(10, 50, 4)
print("Otro array con linspace:", linspace_array2)


**Ejercicios**

Crea un array con números del 0 al 50, cada 5 unidades.


In [ ]:
np.arange(0, 51, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Genera un array con 7 números igualmente espaciados entre 2 y 3.


In [ ]:
np.linspace(2, 3, 7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

Crea un array con números enteros del 10 al 1 en orden descendente.

In [ ]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## 2.4. Arrays Aleatorios

NumPy incluye funciones para generar arrays con números aleatorios, lo cual es útil en simulaciones y pruebas.



In [1]:
import numpy as np

**Ejemplo 1:** Números Aleatorios Uniformes

In [2]:
# Array de forma (2, 3) con números aleatorios entre 0 y 1
random_array = np.random.rand(2, 3)
print("Array aleatorio uniforme:\n", random_array)


Array aleatorio uniforme:
 [[0.55439404 0.60209503 0.99968159]
 [0.03877723 0.83870005 0.60169403]]


**Ejemplo 2:** Números Aleatorios Enteros

In [3]:
# Array de enteros aleatorios entre 1 y 100 de forma (3, 3)
random_int_array = np.random.randint(1, 100, (3, 3))
print("Array aleatorio de enteros:\n", random_int_array)


Array aleatorio de enteros:
 [[31 43 46]
 [40 39 70]
 [89 56 92]]


In [4]:
np.random.rand(3,3) * 2 - 1 # para obtener entre -1 y 1

array([[-0.00830387,  0.160123  , -0.12461324],
       [-0.75096933, -0.91452974, -0.37248492],
       [ 0.31560655,  0.81244711,  0.05562922]])

**Ejercicios**

Genera un array de forma (5,) con números aleatorios entre 0 y 1.


In [ ]:
np.random.rand(5,)

array([0.97694524, 0.24065938, 0.64171499, 0.80227754, 0.22520606])

Crea un array de enteros aleatorios entre 50 y 100 de forma (4, 2).


In [ ]:
np.random.randint(50, 100, (4, 2))

array([[74, 73],
       [68, 80],
       [53, 86],
       [70, 77]])

Genera un array aleatorio de forma (3, 3) y multiplica todos sus elementos por 10.

In [ ]:
np.random.rand(3,3)*10

array([[3.09089909, 0.82885286, 4.89294991],
       [3.22577419, 7.73591454, 4.28503366],
       [5.16734294, 2.68481503, 3.10174952]])

## 3. Propiedades de los Arrays

Es importante comprender las propiedades de los arrays para manipularlos eficazmente.

**Ejemplo 1:** Explorando las Propiedades

In [10]:
### En clase
array3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]]
                 )
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
array2 = np.array([[1, 2, 3],
                  [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [14]:
array3.ndim

3

In [15]:
array3.shape

(2, 3, 3)

In [17]:
array3.dtype

dtype('int64')

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)
print("Dimensiones (ndim):", array.ndim)
print("Forma (shape):", array.shape)
print("Tamaño total (size):", array.size)
print("Tipo de datos (dtype):", array.dtype)


Array:
 [[1 2 3]
 [4 5 6]]
Dimensiones (ndim): 2
Forma (shape): (2, 3)
Tamaño total (size): 6
Tipo de datos (dtype): int64


**Ejemplo 2:** Tamaño en Memoria


In [19]:
print("Tamaño en bytes de un elemento (itemsize):", array.itemsize)
print("Tamaño total en memoria (nbytes):", array.nbytes)


Tamaño en bytes de un elemento (itemsize): 8
Tamaño total en memoria (nbytes): 48


In [20]:
array4 = np.array(['T',
                   'Tamaño en bytes de un elemento (itemsize):',
                   "Tamaño en bytes de un elemento (itemsize):",
                   "Tamaño en bytes de un elemento (itemsize):"])

In [22]:
array4.itemsize


168

In [23]:
array4.nbytes

672

**Ejercicios**

Crea un array de forma (3, 4) y muestra todas sus propiedades.


In [25]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
print("Dimensiones (ndim):", array1.ndim)
print("Forma (shape):", array1.shape)
print("Tamaño total (size):", array1.size)
print("Tipo de datos (dtype):", array1.dtype)
print("Tamaño en bytes de un elemento (itemsize):", array1.itemsize)
print("Tamaño total en memoria (nbytes):", array1.nbytes)

Dimensiones (ndim): 2
Forma (shape): (3, 4)
Tamaño total (size): 12
Tipo de datos (dtype): int64
Tamaño en bytes de un elemento (itemsize): 8
Tamaño total en memoria (nbytes): 96


Cambia el tipo de datos de un array a float64 y verifica el cambio en dtype.


In [35]:
array1_float = array1.astype(np.float64)
print(array1_float.dtype)

float64


In [36]:
array1_float = array1.astype('float64')
print(array1_float.dtype)

float64


Calcula el tamaño total en memoria de un array de forma (1000,) con tipo de datos int32.

In [39]:
array2 = np.arange(0, 1000, dtype=np.int32)
array2.nbytes


4000

In [ ]:
array3 = np.arange(0, 1000, dtype=np.int32)
array2.nbytes

In [46]:
### Mejor respuesta
arrayx = np.random.rand(1000,)*10
arrayx = arrayx.astype('int32')
arrayx

array([6, 0, 4, 7, 0, 9, 1, 6, 9, 7, 7, 6, 1, 4, 3, 6, 1, 1, 9, 1, 3, 3,
       2, 7, 2, 6, 8, 5, 2, 8, 3, 3, 7, 5, 9, 2, 0, 7, 2, 9, 5, 9, 6, 2,
       2, 7, 3, 1, 4, 1, 0, 2, 9, 1, 0, 4, 3, 0, 3, 1, 3, 6, 8, 5, 2, 8,
       2, 3, 2, 2, 3, 3, 6, 0, 6, 0, 8, 6, 9, 9, 3, 9, 1, 6, 0, 9, 4, 6,
       9, 8, 6, 5, 6, 5, 2, 9, 1, 4, 8, 1, 7, 8, 9, 5, 4, 1, 4, 9, 6, 4,
       9, 6, 9, 8, 3, 7, 0, 6, 0, 5, 2, 7, 9, 7, 3, 4, 8, 2, 5, 0, 0, 0,
       8, 8, 4, 8, 9, 8, 9, 6, 6, 7, 2, 5, 4, 9, 9, 5, 9, 9, 4, 6, 9, 8,
       7, 6, 6, 4, 0, 7, 9, 5, 1, 1, 1, 5, 6, 6, 4, 1, 3, 6, 7, 5, 2, 8,
       1, 5, 0, 8, 1, 9, 0, 8, 1, 2, 6, 0, 3, 3, 5, 4, 5, 9, 6, 0, 4, 0,
       6, 9, 2, 1, 8, 7, 7, 9, 6, 7, 0, 0, 5, 6, 7, 5, 3, 0, 7, 3, 1, 2,
       3, 8, 9, 4, 4, 1, 8, 3, 1, 8, 4, 9, 8, 0, 2, 5, 0, 0, 5, 1, 1, 1,
       0, 6, 6, 3, 9, 0, 6, 2, 9, 8, 4, 2, 8, 8, 1, 2, 3, 1, 3, 2, 9, 4,
       2, 1, 9, 4, 4, 0, 0, 2, 1, 9, 3, 8, 7, 2, 5, 3, 1, 5, 4, 6, 8, 3,
       9, 3, 7, 3, 5, 0, 1, 4, 0, 5, 1, 4, 6, 0, 0,

In [47]:
arrayx.nbytes

4000

In [48]:
arrayx.size

1000

In [50]:
arrayn = np.array([np.nan for x in range(0, 1_000)])
arrayn.nbytes

8000

In [51]:
arrayn.dtype

dtype('float64')

## 4. Operaciones Básicas

Las operaciones vectorizadas en NumPy permiten realizar cálculos de forma eficiente sin necesidad de bucles.

### 4.1. Operaciones Matemáticas

**Ejemplo 1:** Operaciones Elemento a Elemento

In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)


Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


**Ejemplo 2:** Operaciones con Escalares

In [53]:
# Multiplicación por un escalar
scalar_mult = a * 10
print("Multiplicación por escalar:", scalar_mult)

# Exponenciación
exp_array = a ** 2
print("Exponenciación:", exp_array)


Multiplicación por escalar: [10 20 30]
Exponenciación: [1 4 9]


In [57]:
### deben tener las mismas dimensiones
a = np.array([1, 2, 3])
b = np.array([1, 2])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

**Ejercicios**

Dado x = np.array([2, 4, 6]) y y = np.array([1, 3, 5]), calcula x * y y x / y.


In [54]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])
print(x * y)
print(x / y)

[ 2 12 30]
[2.         1.33333333 1.2       ]


Eleva al cubo cada elemento del array x.


In [55]:
print(x**3)

[  8  64 216]


Suma 5 a cada elemento del array y y luego calcula la raíz cuadrada.

In [59]:
print(y+5)

[ 6  8 10]


In [58]:
print((y + 5)**0.5)

[2.44948974 2.82842712 3.16227766]


### 4.2. Funciones Matemáticas

NumPy proporciona funciones universales (ufuncs) para realizar operaciones matemáticas.

**Ejemplo 1:** Funciones Estadísticas

In [60]:
array = np.array([1, 5, 2, 8, 3])

print("Suma total:", array.sum())
print("Promedio:", array.mean())
print("Mediana:", np.median(array))
print("Desviación estándar:", array.std())


Suma total: 19
Promedio: 3.8
Mediana: 3.0
Desviación estándar: 2.4819347291981715


In [62]:
array1 = np.array([1, 5, 2, 8, 3])
array2 = np.array([[1, 5, 2, 8, 3], [1, 5, 2, 8, 3]])

In [64]:
array2.sum()

38

In [65]:
array1.sum()/array1.size

3.8

In [66]:
array1.mean()

3.8

In [68]:
array1.std()

2.4819347291981715

In [69]:
np.median(array1)

3.0

**Ejemplo 2:** Funciones Trigonométricas y Exponenciales

In [70]:
angles = np.array([0, np.pi/2, np.pi])

print("Seno:", np.sin(angles))
print("Coseno:", np.cos(angles))
print("Exponencial:", np.exp(array))


Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponencial: [2.71828183e+00 1.48413159e+02 7.38905610e+00 2.98095799e+03
 2.00855369e+01]


In [71]:
array.max()

8

In [72]:
array.min()

1

In [73]:
np.abs(np.array([1, 5, 8, -3]))

array([1, 5, 8, 3])

In [75]:
np.percentile(array, [10 , 2 ,50, 80, 90])

array([1.4 , 1.08, 3.  , 5.6 , 6.8 ])

In [77]:
np.clip(array, a_min = 0, a_max = 5)

array([1, 5, 2, 5, 3])

**Ejercicios**

Calcula el valor máximo y mínimo de un array aleatorio de forma (10,).


Dado un array de ángulos en grados, conviértelos a radianes y calcula su seno.


Genera un array y normalízalo restando la media y dividiendo por la desviación estándar.

## 5. Indexación y Slicing

La indexación y el slicing te permiten acceder y modificar partes específicas de un array.

**Ejemplo 1:** Acceso a Elementos Individuales

In [ ]:
array = np.array([[10, 20, 30], [40, 50, 60]])

# Acceder al elemento en la fila 1, columna 2
element = array[1, 2]
print("Elemento en (1, 2):", element)


**Ejemplo 2:** Slicing de Subarrays

In [ ]:
# Obtener la primera fila
first_row = array[0, :]
print("Primera fila:", first_row)

# Obtener la segunda columna
second_col = array[:, 1]
print("Segunda columna:", second_col)

# Obtener un subarray de forma (2, 2)
subarray = array[:, :2]
print("Subarray:\n", subarray)


**Ejercicios**

Dado un array de forma (5, 5), extrae la submatriz central de forma (3, 3).


Cambia los elementos de la última fila de un array a ceros.


Invierte el orden de los elementos en un array unidimensional.


## 6. Manipulación de la Forma

### 6.1. Reshape

Cambiar la forma de un array sin alterar sus datos.

In [79]:
array = np.array(range(1, 10))
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
array.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
array.reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)

In [82]:
array.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

**Ejemplo 1:** Reshape Básico

In [83]:
array = np.arange(12)
reshaped_array = array.reshape(3, 4)
print("Array reestructurado:\n", reshaped_array)


Array reestructurado:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Ejemplo 2:** Reshape con -1

In [86]:
# NumPy calcula automáticamente el tamaño faltante
reshaped_array = array.reshape(2, -1)
print("Array reestructurado con -1:\n", reshaped_array)


Array reestructurado con -1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


**Ejercicios**

Convierte un array de forma (6,) en uno de forma (2, 3).


Dado un array de forma (4, 3), conviértelo en uno de forma (2, 2, 3).


Aplana un array multidimensional a un array unidimensional.

### 6.2. Transposición

Intercambia los ejes de un array.

**Ejemplo 1:** Transposición de Matriz

In [87]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transposed_matrix = matrix.T
print("Matriz original:\n", matrix)
print("Matriz transpuesta:\n", transposed_matrix)


Matriz original:
 [[1 2]
 [3 4]
 [5 6]]
Matriz transpuesta:
 [[1 3 5]
 [2 4 6]]


**Ejemplo 2:** Transposición de Arrays de Mayor Dimensión

In [89]:
array = np.arange(24).reshape(2, 3, 4)
transposed_array = array.transpose(1, 0, 2)
print("Array transpuesto:\n", transposed_array.shape)


Array transpuesto:
 (3, 2, 4)


In [94]:
array = np.arange(8).reshape(2, 2, 2)
array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
array.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

**Ejercicios**

Transpón una matriz de forma (5, 3).


Dado un array de forma (2, 3, 4), reorganiza sus ejes para obtener un array de forma (4, 2, 3).


Verifica que la transposición de una matriz simétrica es igual a la matriz original.

### 6.3. Concatenación y División de Arrays

Combina o divide arrays.

**Ejemplo 1:** Concatenación

In [97]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenación unidimensional
concat_array = np.concatenate((a, b))
print("Array concatenado:", concat_array)

Array concatenado: [1 2 3 4 5 6]


In [98]:
# Concatenación bidimensional
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

concat_2d = np.concatenate((array1, array2), axis=0)
print("Array 2D concatenado:\n", concat_2d)

Array 2D concatenado:
 [[1 2]
 [3 4]
 [5 6]]


**Ejemplo 2:** División


In [106]:
# División en arrays más pequeños
split_array = np.array_split(concat_array, 3)
print("Arrays divididos:", split_array)


Arrays divididos: [array([1, 2]), array([3, 4]), array([5, 6])]


**Ejercicios**

Une dos matrices de forma (2, 2) para crear una de forma (2, 4).


Divide un array de forma (12,) en tres arrays iguales.


Combina verticalmente dos arrays de forma (3, 2).

## 7. Broadcasting

El broadcasting permite realizar operaciones entre arrays de diferentes formas.

**Ejemplo 1:** Suma con Broadcasting

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

result = a + b
print("Resultado de broadcasting:\n", result)


**Ejemplo 2:** Multiplicación con Broadcasting

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

result = array * scalar
print("Multiplicación por escalar:\n", result)


Ejercicios

Suma un vector de forma (3,) a una matriz de forma (3, 3).


Multiplica cada columna de una matriz de forma (4, 3) por un vector de forma (3,).


Resta un escalar de todos los elementos de un array.


## 8. Álgebra Lineal

NumPy proporciona funciones avanzadas para realizar operaciones de álgebra lineal.



### 8.1. Producto Punto y Producto Cruz

**Ejemplo 1:** Producto Punto


In [107]:
vector1 = np.array([1, 2])
vector2 = np.array([3, 4])

In [108]:
vector1 * vector2

array([3, 8])

In [110]:
vector1 @ vector2

11

In [111]:
dot_product = np.dot(vector1, vector2)
print("Producto punto:", dot_product)

Producto punto: 11


In [112]:
vector1 = np.array([1, 2, 4])
vector2 = np.array([3, 4, 6])
np.dot(vector1, vector2)

35

**Ejemplo 2:** Producto Cruz

In [ ]:
vector3 = np.array([1, 0, 0])
vector4 = np.array([0, 1, 0])

In [ ]:
cross_product = np.cross(vector3, vector4)
print("Producto cruz:", cross_product)

**Ejercicios**

Calcula el producto punto de dos vectores de dimensión 3.


Encuentra el producto cruz de los vectores [2, 3, 4] y [5, 6, 7].


Verifica que el producto punto de dos vectores perpendiculares es cero.

### 8.2. Operaciones con Matrices

**Ejemplo 1:**  Multiplicación de Matrices

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 2]])

product = np.matmul(matrix1, matrix2)
print("Producto de matrices:\n", product)


**Ejemplo 2:** Inversa y Determinante

In [ ]:
matrix = np.array([[4, 7], [2, 6]])

# Inversa
inverse = np.linalg.inv(matrix)
print("Inversa de la matriz:\n", inverse)

# Determinante
determinant = np.linalg.det(matrix)
print("Determinante de la matriz:", determinant)


**Ejercicios**

Calcula el determinante de una matriz de 3x3.


Encuentra la matriz inversa de una matriz cuadrada.


Verifica que el producto de una matriz y su inversa es la matriz identidad.

### 8.3. Sistemas de Ecuaciones Lineales

Resuelve sistemas de ecuaciones lineales utilizando NumPy.


